let produtos = [
    {
        titulo: "Falcomon",
        forma: "Forma: Rookie",
        atributo: "/imersão alura/AluraGemini/imagens/atributo/VA.png",
        descAtributo: "Vacina",
        familia: "/imersão alura/AluraGemini/imagens/familia/WG.png",
        descFamilia:"Wind Guardians",
        forca: "/imersão alura/AluraGemini/imagens/força/wind.png",
        descForca: "Dobra sua chance de evasão contra este elemento",
        fraqueza: "/imersão alura/AluraGemini/imagens/fraqueza/fire.png",
        descFraqueza: "Aumenta o dano recebido deste elemento em 25%",
        descricao: "Status no lvl 90",
        hp: "HP: 1690",
        sp: "SP: 611",
        str: "STR: 281",
        int: "INT: 319",
        def: "DEF: 254",
        res: "RES: 257",
        spd: "SPD: 180",
        imagem: "/imersão alura/AluraGemini/imagens/rookie/Falcomon.png",
        tags: "falcomon rookie",
        seta: "/imersão alura/AluraGemini/imagens/setas/setaBaixo.png",
        evo1: "/imersão alura/AluraGemini/imagens/rookie/Falcomon.png",
        nomeEvo1: "Falcomon",
        evo2: "/imersão alura/AluraGemini/imagens/champion/Peckmon.png",
        nomeEvo2: "Peckmon",
        evo3: "/imersão alura/AluraGemini/imagens/ultimate/Yatagaramon.png",
        nomeEvo3: "Yatagaramon",
        evo4: "/imersão alura/AluraGemini/imagens/mega/Ravemon.png",
        nomeEvo4: "Ravemon"
    },
    {        
        titulo: "Peckmon",
        forma: "Forma: Champion",
        atributo: "/imersão alura/AluraGemini/imagens/atributo/VA.png",
        descAtributo: "Vacina",
        familia: "/imersão alura/AluraGemini/imagens/familia/WG.png",
        descFamilia:"Wind Guardians",
        forca: "/imersão alura/AluraGemini/imagens/força/wind.png",
        descForca: "Dobra sua chance de evasão contra este elemento",
        fraqueza: "/imersão alura/AluraGemini/imagens/fraqueza/fire.png",
        descFraqueza: "O dano recebido desse elemento não pode ser esquivado",
        descricao: "Status no lvl 90",
        hp: "HP: 2418",
        sp: "SP: 952",
        str: "STR: 531",
        int: "INT: 448",
        def: "DEF: 389",
        res: "RES: 384",
        spd: "SPD: 286",
        imagem: "/imersão alura/AluraGemini/imagens/champion/Peckmon.png",
        tags: "peckmon champion",
        seta: "/imersão alura/AluraGemini/imagens/setas/setaBaixo.png",
        evo1: "/imersão alura/AluraGemini/imagens/rookie/Falcomon.png",
        nomeEvo1: "Falcomon",
        evo2: "/imersão alura/AluraGemini/imagens/champion/Peckmon.png",
        nomeEvo2: "Peckmon",
        evo3: "/imersão alura/AluraGemini/imagens/ultimate/Yatagaramon.png",
        nomeEvo3: "Yatagaramon",
        evo4: "/imersão alura/AluraGemini/imagens/mega/Ravemon.png",
        nomeEvo4: "Ravemon"  
    },
    {
        titulo: "Yatagaramon",
        forma: "Forma: Ultimate",
        atributo: "/imersão alura/AluraGemini/imagens/atributo/VA.png",
        descAtributo: "Vacina",
        familia: "/imersão alura/AluraGemini/imagens/familia/WG.png",
        descFamilia:"Wind Guardians",
        forca: "/imersão alura/AluraGemini/imagens/força/thunder.png",
        descForca: "O dano recebido desse elemento é reduzido em 25%",
        fraqueza: "/imersão alura/AluraGemini/imagens/fraqueza/fire.png",
        descFraqueza: "Aumenta o dano recebido deste elemento em 25%",
        descricao: "Status no lvl 90",
        hp: "HP: 3503",
        sp: "SP: 1408",
        str: "STR: 681",
        int: "INT: 721",
        def: "DEF: 572",
        res: "RES: 624",
        spd: "SPD: 346",
        imagem: "/imersão alura/AluraGemini/imagens/ultimate/Yatagaramon.png",
        tags: "peckmon champion",
        seta: "/imersão alura/AluraGemini/imagens/setas/setaBaixo.png",
        evo1: "/imersão alura/AluraGemini/imagens/rookie/Falcomon.png",
        nomeEvo1: "Falcomon",
        evo2: "/imersão alura/AluraGemini/imagens/champion/Peckmon.png",
        nomeEvo2: "Peckmon",
        evo3: "/imersão alura/AluraGemini/imagens/ultimate/Yatagaramon.png",
        nomeEvo3: "Yatagaramon",
        evo4: "/imersão alura/AluraGemini/imagens/mega/Ravemon.png",
        nomeEvo4: "Ravemon"
    },
    {
        titulo: "Agumon",
        forma: "Forma: Rookie",
        atributo: "/imersão alura/AluraGemini/imagens/atributo/VA.png",
        descAtributo: "Vacina",
        familia: "/imersão alura/AluraGemini/imagens/familia/dr.png",
        familia2: "/imersão alura/AluraGemini/imagens/familia/me.png",
        familia3: "/imersão alura/AluraGemini/imagens/familia/vb.png",
        descFamilia:"Wind Guardians",
        forca: "/imersão alura/AluraGemini/imagens/força/wind.png",
        descForca: "O dano recebido desse elemento é reduzido em 25%",
        fraqueza: "/imersão alura/AluraGemini/imagens/fraqueza/water.png",
        descFraqueza: "Aumenta o dano recebido deste elemento em 25%",
        descricao: "Status no lvl 90",
        hp: "HP: 2689",
        sp: "SP: 560",
        str: "STR: 373",
        int: "INT: 205",
        def: "DEF: 336",
        res: "RES: 317",
        spd: "SPD: 140",
        imagem: "/imersão alura/AluraGemini/imagens/rookie/Agumon.png",
        tags: "peckmon champion",
        seta: "/imersão alura/AluraGemini/imagens/setas/setaBaixo.png",
        evo1: "/imersão alura/AluraGemini/imagens/rookie/Agumon.png",
        nomeEvo1: "Agumon",
        evo2: "/imersão alura/AluraGemini/imagens/champion/Greymon.png",
        nomeEvo2: "Greymon",
        evo3: "/imersão alura/AluraGemini/imagens/ultimate/Metalgreymon.png",
        nomeEvo3: "Metal Greymon",
        evo4: "/imersão alura/AluraGemini/imagens/mega/Wargreymon.png",
        nomeEvo4: "War Greymon"
    }
];